package Report;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author PRAJWAL PRABHU
 */
import connections.DatabaseConnection;
import depot.Mainpage_depot;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import mainpage1.*;
import java.sql.*;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private DatabaseConnection db;

    public MainFrame() {
        initComponents();
        db = new DatabaseConnection();
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(Color.decode("#C539B4"));
        tableuserreport.setBackground(Color.decode("#EF9A53"));
        tableuserreport.setSelectionBackground(Color.decode("#F5D5AE"));

        headerRenderer.setPreferredSize(new Dimension(100, 40));
        headerRenderer.setForeground(Color.BLACK);
        headerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tableuserreport.setRowHeight(30);
        tableuserreport.setDefaultRenderer(Object.class, centerRenderer);
        tableuserreport.getTableHeader().setDefaultRenderer(headerRenderer);
        tableuserreport.getTableHeader().setFont(new Font("Sanserif", Font.BOLD, 17));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel reportpanel = new javax.swing.JPanel();
        javax.swing.JPanel reportentrypanel = new javax.swing.JPanel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        tfruserid = new javax.swing.JTextField();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        tfrreportid = new javax.swing.JTextField();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        tfrdoctorid = new javax.swing.JTextField();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        tfrsnf = new javax.swing.JTextField();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        tfrclr = new javax.swing.JTextField();
        javax.swing.JButton btnrclear = new javax.swing.JButton();
        javax.swing.JButton btnradd = new javax.swing.JButton();
        tfrfat = new javax.swing.JTextField();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        rdatechooser = new com.toedter.calendar.JDateChooser();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        tfrlocation = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        javax.swing.JPanel reportupanel = new javax.swing.JPanel();
        javax.swing.JLabel rheadlabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        tableuserreport = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        reportpanel.setBackground(new java.awt.Color(255, 255, 255));
        reportpanel.setMinimumSize(new java.awt.Dimension(1920, 1080));
        reportpanel.setPreferredSize(new java.awt.Dimension(1920, 1080));
        reportpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reportentrypanel.setBackground(new java.awt.Color(204, 204, 0));
        reportentrypanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New Report", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 1, 14))); // NOI18N
        reportentrypanel.setForeground(new java.awt.Color(255, 255, 255));
        reportentrypanel.setToolTipText("");
        reportentrypanel.setAlignmentY(4.0F);
        reportentrypanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setText("USER_ID :");
        reportentrypanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 100, 40));

        tfruserid.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tfruserid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfruserid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfruseridActionPerformed(evt);
            }
        });
        reportentrypanel.add(tfruserid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 64, 190, 40));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setText("REPORT_ID :");
        reportentrypanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 120, -1));

        tfrreportid.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tfrreportid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfrreportid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfrreportidActionPerformed(evt);
            }
        });
        reportentrypanel.add(tfrreportid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 124, 190, 40));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setText("DOCTOR_ID :");
        reportentrypanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 120, -1));

        tfrdoctorid.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tfrdoctorid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reportentrypanel.add(tfrdoctorid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 184, 190, 40));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setText("FAT(%) :");
        reportentrypanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 90, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setText("SNF(%) :");
        reportentrypanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 80, -1));

        tfrsnf.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tfrsnf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reportentrypanel.add(tfrsnf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 190, 40));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setText("CLR('c) :");
        reportentrypanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 79, -1));

        tfrclr.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tfrclr.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reportentrypanel.add(tfrclr, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 190, 40));

        btnrclear.setBackground(new java.awt.Color(255, 255, 204));
        btnrclear.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnrclear.setForeground(new java.awt.Color(255, 0, 0));
        btnrclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/erase.png"))); // NOI18N
        btnrclear.setText("CLEAR");
        btnrclear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnrclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrclearActionPerformed(evt);
            }
        });
        reportentrypanel.add(btnrclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 590, 130, 40));

        btnradd.setBackground(new java.awt.Color(255, 255, 204));
        btnradd.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnradd.setForeground(new java.awt.Color(255, 0, 0));
        btnradd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnradd.setText("ADD");
        btnradd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnradd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnraddActionPerformed(evt);
            }
        });
        reportentrypanel.add(btnradd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 120, 40));

        tfrfat.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        reportentrypanel.add(tfrfat, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 190, 40));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setText("DATE :");
        reportentrypanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 64, -1));

        rdatechooser.setBackground(new java.awt.Color(242, 248, 248));
        rdatechooser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        reportentrypanel.add(rdatechooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 190, 30));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel9.setText("LOCATION :  ");
        reportentrypanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 130, -1));

        tfrlocation.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        reportentrypanel.add(tfrlocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 190, 40));

        reportpanel.add(reportentrypanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 450, 660));
        reportpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4359, 6, 37, -1));

        reportupanel.setBackground(new java.awt.Color(0, 153, 0));
        reportupanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reportupanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rheadlabel.setBackground(new java.awt.Color(102, 102, 102));
        rheadlabel.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        rheadlabel.setForeground(new java.awt.Color(255, 255, 255));
        rheadlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rheadlabel.setText("Fill User Report");
        rheadlabel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        reportupanel.add(rheadlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 1380, 70));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-thick-long-left-arrow-70.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        reportupanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 80, 70));

        reportpanel.add(reportupanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1610, 90));

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableuserreport.setBackground(new java.awt.Color(204, 255, 204));
        tableuserreport.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        tableuserreport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "USER_ID", "REPORT_ID", "DOCTOR_ID", "LOCATION", "FAT", "SNF", "CLR", "DATE"
            }
        ));
        tableuserreport.setFocusable(false);
        tableuserreport.setOpaque(false);
        tableuserreport.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableuserreport);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 900, 440));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-70.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 530, 90, 90));

        reportpanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 990, 650));

        jLabel11.setBackground(new java.awt.Color(255, 204, 204));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/userho.jpg"))); // NOI18N
        reportpanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1610, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reportpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1612, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reportpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        //used when we close application it is used to save data

    }//GEN-LAST:event_formWindowClosing
    Connection conn = null;

    private Connection getNewConnection() {
        conn = db.getConnection();
        return conn;
    }

    public void fetchtable() {
        Connection conn = null;
        try {
            conn = getNewConnection();
            String query = "SELECT r.User_Id, r.Report_Id, rd.Doctor_Id, r.Local_Loc, r.Fat, r.SNF, r.CLR, rd.Report_Date FROM Report r INNER JOIN Reportdate rd ON r.Report_Id = rd.Report_Id";
            PreparedStatement pst = conn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tableuserreport.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                String user_id = rs.getString("User_Id");
                String report_id = rs.getString("Report_Id");
                String doctor_id = rs.getString("Doctor_Id");
                String local_loc = rs.getString("Local_Loc");
                float fat = rs.getFloat("Fat");
                float snf = rs.getFloat("SNF");
                float clr = rs.getFloat("CLR");
                Date report_date = rs.getDate("Report_Date");
                model.addRow(new Object[]{user_id, report_id, doctor_id, local_loc, fat, snf, clr, report_date});
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error occured ", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

    }

    private void btnraddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnraddActionPerformed
        // TODO add your handling code here:
        String reportId = tfrreportid.getText();
        String userId = tfruserid.getText();
        String doctorId = tfrdoctorid.getText();
        String location = tfrlocation.getText();
        String fat = tfrfat.getText();
        String snf = tfrsnf.getText();
        String clr = tfrclr.getText();
        
//        String date1=rdatechooser.getDate()
        String date = new SimpleDateFormat("dd-MM-yyyy").format(rdatechooser.getDate());
        System.out.println(date);
        if (rdatechooser.getDate() == null || tfruserid.getText().isEmpty() || tfrdoctorid.getText().isEmpty() || tfrlocation.getText().isEmpty() || tfrfat.getText().isEmpty() || tfrsnf.getText().isEmpty() || tfrclr.getText().isEmpty() || tfrreportid.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Cannot proceed, please enter all fields.", "Error", JOptionPane.ERROR_MESSAGE);

        } else {
            Connection conn = getNewConnection();
            try {
                // Check if the entered Report ID already exists in Report table
                String checkReportId = "SELECT COUNT(*) FROM Report WHERE Report_Id = ?";
                PreparedStatement checkReportIdPstmt = conn.prepareStatement(checkReportId);
                checkReportIdPstmt.setString(1, reportId);
                ResultSet checkReportIdRs = checkReportIdPstmt.executeQuery();
                checkReportIdRs.next();
                int count = checkReportIdRs.getInt(1);
                if (count > 0) {
                    JOptionPane.showMessageDialog(null, "Report ID already exists, please enter a different ID.");
                    return;
                }

                // Check if the entered location matches with the location of the user in Dairyfarmer table
                String checkUserLocation = "SELECT COUNT(*) FROM Dairyfarmer WHERE Local_Loc = ? and User_Id = ?";
                PreparedStatement checkUserLocationPstmt = conn.prepareStatement(checkUserLocation);
                checkUserLocationPstmt.setString(1, location);
                checkUserLocationPstmt.setString(2, userId);
                ResultSet checkUserLocationRs = checkUserLocationPstmt.executeQuery();
                checkUserLocationRs.next();
                int count1 = checkUserLocationRs.getInt(1);
                if (count1 < 1) {
                    JOptionPane.showMessageDialog(null, "User depot does not match the entered location, please check and enter again.");
                    return;
                }
                String checkReportDate = "SELECT COUNT(*) FROM Reportdate WHERE Report_Id = ? and Report_Date = ?";
                PreparedStatement checkReportDatePstmt = conn.prepareStatement(checkReportDate);
                checkReportDatePstmt.setString(1, reportId);
                checkReportDatePstmt.setString(2, date);
                ResultSet checkReportDateRs = checkReportDatePstmt.executeQuery();
                checkReportDateRs.next();
                int count2 = checkReportDateRs.getInt(1);
                if (count2 > 0) {
                    JOptionPane.showMessageDialog(null, "The date has already been entered for the given Report ID, please enter a different date.");
                    return;
                }
                // Insert values into Report table
                String reportQuery = "INSERT INTO Report(Report_Id, Fat, SNF, CLR, User_Id, Local_Loc) VALUES (?, ?, ?, ?, ?, ?)";
                PreparedStatement reportPstmt = conn.prepareStatement(reportQuery);
                reportPstmt.setString(1, reportId);
                reportPstmt.setString(2, fat);
                reportPstmt.setString(3, snf);
                reportPstmt.setString(4, clr);
                reportPstmt.setString(5, userId);
                reportPstmt.setString(6, location);
                reportPstmt.executeUpdate();

                // Insert values into Reportdate table
                String reportdateQuery = "INSERT INTO Reportdate(Report_Id, Report_Date, Doctor_Id)VALUES (?, ?, ?)";
                PreparedStatement reportdatePstmt = conn.prepareStatement(reportdateQuery);
                reportdatePstmt.setString(1, reportId);
                reportdatePstmt.setString(2, date);
                reportdatePstmt.setString(3, doctorId);
                reportdatePstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data inserted successfully!");
                fetchtable();

            } 
//            catch (NullPointerException e) {
//                JOptionPane.showMessageDialog(null, "Enter all the fields.");}
             catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Looks like something went wrong .");
                e.printStackTrace();
            }

            // Check if the entered date
            tfruserid.setText("");
            tfrreportid.setText("");
            tfrdoctorid.setText("");       //To enter values in text fields
            tfrfat.setText("");
            tfrsnf.setText("");
            tfrclr.setText("");
            tfrlocation.setText("");
            rdatechooser.setDate(null);
    }//GEN-LAST:event_btnraddActionPerformed
    }
    private void btnrclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrclearActionPerformed
        // TODO add your handling code here:
        //To clear entered values

        tfruserid.setText("");
        tfrreportid.setText("");
        tfrdoctorid.setText("");
        tfrlocation.setText(""); //To enter values in text fields
        tfrfat.setText("");
        tfrsnf.setText("");
        tfrclr.setText("");
        rdatechooser.setDate(null);

    }//GEN-LAST:event_btnrclearActionPerformed
    private void rdatechooserActionPerformed(java.awt.event.ActionEvent evt) {
        //Retrieve the selected date from the JDateChooser
        Date selectedDate = rdatechooser.getDate();
        // Use the SimpleDateFormat to format the date
        SimpleDateFormat formatter = new SimpleDateFormat("MM-dd-yyyy");
        String dateString = formatter.format(selectedDate);
        // Now you can insert dateString into the table 
        // or use it as per your requirement
    }
    private void tfruseridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfruseridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfruseridActionPerformed

    private void tfrreportidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfrreportidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfrreportidActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        Mainpage_depot mainpageDepot = new Mainpage_depot();
        mainpageDepot.setVisible(true);
        dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        new Mainpage().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private Mainpage_depot mainpageDepot;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private com.toedter.calendar.JDateChooser rdatechooser;
    private javax.swing.JTable tableuserreport;
    private javax.swing.JTextField tfrclr;
    private javax.swing.JTextField tfrdoctorid;
    private javax.swing.JTextField tfrfat;
    private javax.swing.JTextField tfrlocation;
    private javax.swing.JTextField tfrreportid;
    private javax.swing.JTextField tfrsnf;
    private javax.swing.JTextField tfruserid;
    // End of variables declaration//GEN-END:variables
}
