/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mainpage1;

import connections.DatabaseConnection;
import java.awt.print.PrinterException;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */

public class Mainpage_User_Report extends javax.swing.JFrame {

    /**
     * Creates new form Mainpage_User_Report
     */
    String copiedText1;
    String copiedText2;
    private DatabaseConnection db;
    static String userId;

    public Mainpage_User_Report(String userId) {
        initComponents();
        db = new DatabaseConnection();
        jPanel4.setVisible(false);
        this.userId = userId;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "INFORMATION", "VALUES"
            }
        ));
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel9.setText("Date :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel10.setText("User id :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel11.setText("User name :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel12.setText("Report id :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel13.setText("Doctor id :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, 20));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel14.setText("Fat( %) :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, 20));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setText("SNF( %) :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, -1, -1));

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel15.setText("CNF('C) :");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, -1, -1));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 160, 30));

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 215, 160, 30));

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 265, 160, 30));

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 315, 160, 30));

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 365, 160, 30));

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 415, 160, 30));

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jPanel2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 465, 160, 30));

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("SUGGESTION :");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REPORT");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 960, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setText("Manufacturer id :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, -1, -1));

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, 140, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-cow-100.png"))); // NOI18N
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 540, 130, 120));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setText("Feed Manufacturer");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 670, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 153, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-clone-figure-20.png"))); // NOI18N
        jButton2.setText("Copy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jTextField10.setEditable(false);
        jTextField10.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 140, 40));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setText("Item no:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 360, 190));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cowimageusrrep.jpg"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 510, 370));
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 160, 40));

        jButton3.setBackground(new java.awt.Color(153, 255, 153));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-ok-button-40.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 40, 40));

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-acrobat-80.png"))); // NOI18N
        jLabel16.setText("Print");
        jLabel16.setToolTipText("");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.setFocusTraversalPolicyProvider(true);
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 590, 80, 110));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 960, 710));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-thick-long-left-arrow-70.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, 80));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgr3.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 800));

        jTable2.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Information", "Values"
            }
        ));
        jTable2.setRowHeight(30);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        jPanel4.add(jScrollPane2);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 80, 480, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed
    Connection conn = null;

    private Connection getNewConnection() {
        conn = db.getConnection();
        return conn;
    }
    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (jTextField3.getText().isEmpty() || jTextField3.getText().isEmpty() || jTextField4.getText().isEmpty() || jTextField5.getText().isEmpty() || jTextField6.getText().isEmpty() || jTextField7.getText().isEmpty() || jTextField8.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Fill the details to proceed");
        } else {
            setVisible(false);

            Mainpage_User_FeedM mufm = new Mainpage_User_FeedM(copiedText1, copiedText2);
            mufm.setVisible(true);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        setVisible(false);
        new Mainpage_User().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        copiedText1 = jTextField9.getText();
        copiedText2 = jTextField10.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (jDateChooser1.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Enter the date");
        } else {
            try {
                Connection connection = getNewConnection();

                PreparedStatement checkPS = connection.prepareStatement("SELECT Report_Id FROM Reportdate WHERE Report_Date = ? and Report_Id in (SELECT Report_Id FROM Report WHERE User_Id = ?)");
                checkPS.setDate(1, new java.sql.Date(jDateChooser1.getDate().getTime()));

                checkPS.setString(2, userId);

                ResultSet checkRS = checkPS.executeQuery();

                if (checkRS.next()) {
                    String reportId = checkRS.getString("Report_Id");
                    jTextField4.setText(reportId);

                    // fetch user id, doctor id, fat, snf, clr from Report table
                    PreparedStatement fetchPS = connection.prepareStatement("SELECT User_Id, Fat, SNF, CLR FROM Report WHERE Report_Id = ? and user_id = ?");
                    fetchPS.setString(1, reportId);
                    fetchPS.setString(2, userId);
                    System.out.println(userId);

                    ResultSet fetchRS = fetchPS.executeQuery();

                    if (fetchRS.next()) {

                        userId = fetchRS.getString("User_Id");

                        double fat = fetchRS.getDouble("Fat");
                        double snf = fetchRS.getDouble("SNF");
                        double clr = fetchRS.getDouble("CLR");
                        jTextField2.setText(userId);
                        jTextField6.setText(String.valueOf(fat));
                        jTextField7.setText(String.valueOf(snf));
                        jTextField8.setText(String.valueOf(clr));
                    }

                    // fetch doctor id from Reportdate table
                    PreparedStatement fetchDoctorPS = connection.prepareStatement("SELECT Doctor_Id FROM Reportdate WHERE Report_Id = ?");
                    fetchDoctorPS.setString(1, reportId);
                    ResultSet fetchDoctorRS = fetchDoctorPS.executeQuery();
                    if (fetchDoctorRS.next()) {
                        String doctorId = fetchDoctorRS.getString("Doctor_Id");
                        jTextField5.setText(doctorId);
                    }
                    // fetch user name, local loc from Dairyfarmer table
                    PreparedStatement fetchUserPS = connection.prepareStatement("SELECT User_Name, Local_Loc FROM Dairyfarmer WHERE User_Id = ?");
                    fetchUserPS.setString(1, userId);
                    ResultSet fetchUserRS = fetchUserPS.executeQuery();
                    if (fetchUserRS.next()) {
                        String userName = fetchUserRS.getString("User_Name");
                        String localLoc = fetchUserRS.getString("Local_Loc");
                        jTextField3.setText(userName);
                    }
                    // fetch manu id, item no from Suggestion table
                    PreparedStatement fetchSuggestionPS = connection.prepareStatement("SELECT Manu_Id, Item_No FROM Suggestion WHERE Report_Id = ?");
                    fetchSuggestionPS.setString(1, reportId);
                    System.out.println(reportId);
                    ResultSet fetchSuggestionRS = fetchSuggestionPS.executeQuery();
                    if (fetchSuggestionRS.next()) {
                        String manuId = fetchSuggestionRS.getString("Manu_Id");
                        System.out.println(manuId);
                        String itemNo = fetchSuggestionRS.getString("Item_No");
                        jTextField9.setText(manuId);
                        jTextField10.setText(itemNo);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Report Id on this date does not exist");
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
                    jTextField5.setText("");
                    jTextField6.setText("");
                    jTextField7.setText("");
                    jTextField8.setText("");
                    jTextField9.setText("");
                    jTextField10.setText("");
                }
            } catch (SQLException e) {
//                JOptionPane.showMessageDialog(null, "Report Id on this date does not exist");
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        String date = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();                 
        jPanel4.setVisible(true);
    String userId = jTextField2.getText();
    String username = jTextField3.getText();
    String reportId = jTextField4.getText();
    String doctorId = jTextField5.getText();
    String fat = jTextField6.getText();
    String snf = jTextField7.getText();
    String clr = jTextField8.getText();
    String manufacturerId = jTextField9.getText();
    String itemNo = jTextField10.getText();
     jPanel4.setVisible(true);
    DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
    if (!date.isEmpty() && !userId.isEmpty() && !username.isEmpty() && !reportId.isEmpty() && !doctorId.isEmpty() && !fat.isEmpty() && !snf.isEmpty() && !clr.isEmpty() && !manufacturerId.isEmpty() && !itemNo.isEmpty()) {
        model.setRowCount(0);
        model.addRow(new Object[]{"MILK QUALITY REPORT :"});
        model.addRow(new Object[]{"Date :", date});
        model.addRow(new Object[]{"User Id :", userId});
        model.addRow(new Object[]{"Username :", username});
        model.addRow(new Object[]{"Report Id :", reportId});
        model.addRow(new Object[]{"Doctor Id :", doctorId});
        model.addRow(new Object[]{"Fat :", fat});
        model.addRow(new Object[]{"SNF :", snf});
        model.addRow(new Object[]{"CLR :", clr});
        model.addRow(new Object[]{"Manufacturer Id :", manufacturerId});
        model.addRow(new Object[]{"Item No :", itemNo});
        try {
    boolean complete = jTable2.print();
     
    if (complete) {
        
        JOptionPane.showMessageDialog(null, "Print Success, Downloading the file.");
         jPanel4.setVisible(false);
        
    } else {
         
        JOptionPane.showMessageDialog(null, "Print Cancelled.");
        jPanel4.setVisible(false);
        
    }
} catch (PrinterException pe) {
    JOptionPane.showMessageDialog(null, "Print Exception Occurred.");
    jPanel4.setVisible(false);
    
}

    } else {
        JOptionPane.showMessageDialog(null, "Fields must be filled to generate the report.");
        jPanel4.setVisible(false);
    }
    
    }//GEN-LAST:event_jLabel16MouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainpage_User_Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainpage_User_Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainpage_User_Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainpage_User_Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Mainpage_User_Report(userId).setVisible(true);
       
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
