/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mainpage1;

import connections.DatabaseConnection;
import java.util.Random;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.JTabbedPane;

/**
 *
 * @author hp
 */
public class Signuplogin_page extends javax.swing.JFrame {

    /**
     * Creates new form Signuplogin_page
     */
    private DatabaseConnection db;

    public Signuplogin_page() {
        initComponents();
        db = new DatabaseConnection();
     

        Sginuppanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        Sginuppanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jTextField2 = new javax.swing.JTextField();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel32 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jPasswordField4 = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Localloc = new javax.swing.JTextField();
        jPasswordField5 = new javax.swing.JPasswordField();
        jPasswordField6 = new javax.swing.JPasswordField();
        jLabel20 = new javax.swing.JLabel();
        Depotid = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        Location = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jPasswordField7 = new javax.swing.JPasswordField();
        jPasswordField8 = new javax.swing.JPasswordField();
        jTextField8 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel27 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("SansSerif", 1, 34)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 0, 0));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("COW Health And MILK Quality Tracking System ");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 50));

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setEnabled(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome User !!");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1200, 70));

        jButton5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-login-100.png"))); // NOI18N
        jButton5.setText("Login");
        jButton5.setToolTipText("Login");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 140, 140));

        jButton6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-sign-up-100.png"))); // NOI18N
        jButton6.setText("SignUp");
        jButton6.setToolTipText("Signup,If you are a New User");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 170, 130, 130));

        Sginuppanel.setBackground(new java.awt.Color(255, 153, 0));
        Sginuppanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-user1-100 (1).png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Sginuppanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 120, 120));

        jButton2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-manufacturer-80.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Sginuppanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 130, 120));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-depot-80.png"))); // NOI18N
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Sginuppanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 130, 120));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-medical-doctor-80.png"))); // NOI18N
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Sginuppanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 70, 120, 120));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setText("User");
        Sginuppanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setText("Feed Manufacturer");
        Sginuppanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setText("Milk Depot");
        Sginuppanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 106, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setText("Cow Doctor");
        Sginuppanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 200, 112, -1));

        jPanel2.add(Sginuppanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 1060, 260));

        jPanel15.setBackground(new java.awt.Color(153, 255, 153));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 1060, 210));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signup0.jpg"))); // NOI18N
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 680));

        jTabbedPane1.addTab("", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(102, 255, 102));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jPanel6.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 210, 40));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setText("USER NAME :");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 130, 40));

        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel6.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 210, 40));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setText(" PASSWORD :");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 140, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CONFIRM PASSWORD :");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        jPasswordField2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jPanel6.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 210, 40));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jPanel6.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 210, 40));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel10.setText("YOUR USER ID :");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, -1, -1));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-accept-60.png"))); // NOI18N
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 60, 60));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-proceed-70.png"))); // NOI18N
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 90, 80));

        jTextField5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jPanel6.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 210, 40));

        jLabel37.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel37.setText("Your Location :");
        jPanel6.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 740, 510));

        jPanel11.setBackground(new java.awt.Color(0, 204, 204));

        jLabel6.setBackground(new java.awt.Color(51, 0, 153));
        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("USER SIGNUP");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jPanel3.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 80));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-thick-long-left-arrow-70.png"))); // NOI18N
        jLabel30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 70, 80));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tinywow_sigup21.jpg"))); // NOI18N
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1200, 600));

        jTabbedPane1.addTab("", jPanel3);

        jPanel4.setBackground(new java.awt.Color(51, 255, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("FEED MANUFACTURER SIGNUP");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1200, -1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 51));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel12.setText("MANUFACTURERS  NAME :");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 270, -1));

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel13.setText("PASSWORD :");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel14.setText("CONFIRM PASSWORD :");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jTextField3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jPanel8.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 180, 40));

        jPasswordField3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel8.add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 151, 180, 40));

        jPasswordField4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel8.add(jPasswordField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 231, 180, 40));

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel15.setText("YOUR MAN ID :");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, -1, -1));

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jPanel8.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 392, 180, 40));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-accept-60.png"))); // NOI18N
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 60, 60));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-proceed-70.png"))); // NOI18N
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 90, 80));

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 740, 510));

        jPanel10.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 80));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-thick-long-left-arrow-70.png"))); // NOI18N
        jLabel31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 70, 80));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signup4.jpg"))); // NOI18N
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1200, 600));

        jTabbedPane1.addTab("", jPanel4);

        jPanel5.setBackground(new java.awt.Color(153, 0, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(204, 204, 0));

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("DEPOT ADMIN SIGNUP :");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 80));

        jPanel12.setBackground(new java.awt.Color(255, 102, 102));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel17.setText("DEPOT LOCATION :");
        jLabel17.setToolTipText("");
        jPanel12.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 190, 30));

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel18.setText("CREATE PASSWORD :");
        jPanel12.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 210, 30));

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel19.setText("CONFIRM PASSWORD :");
        jPanel12.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        Localloc.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jPanel12.add(Localloc, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 200, 40));

        jPasswordField5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel12.add(jPasswordField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 200, 40));

        jPasswordField6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel12.add(jPasswordField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 200, 40));

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel20.setText("YOUR DEPOT ID :");
        jPanel12.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, -1, -1));

        Depotid.setEditable(false);
        Depotid.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jPanel12.add(Depotid, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 200, 40));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-accept-60.png"))); // NOI18N
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 60, 60));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-proceed-70.png"))); // NOI18N
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 90, 80));

        jLabel26.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel26.setText("TALUK DEPOT LOCATION :");
        jLabel26.setToolTipText("");
        jPanel12.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 250, 30));

        Location.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jPanel12.add(Location, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 52, 200, 40));

        jPanel5.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 740, 510));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-thick-long-left-arrow-70.png"))); // NOI18N
        jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 70, 80));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signup3.jpg"))); // NOI18N
        jPanel5.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1200, 600));

        jTabbedPane1.addTab("", jPanel5);

        jPanel7.setBackground(new java.awt.Color(204, 255, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("DOCTOR SIGNUP");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 29, 1200, -1));

        jPanel13.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 80));

        jPanel14.setBackground(new java.awt.Color(0, 153, 0));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel22.setText("DOCTOR NAME :");
        jPanel14.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel23.setText("CREATE PASSWORD :");
        jPanel14.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        jLabel24.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel24.setText("CONFIRM PASSWORD :");
        jPanel14.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        jLabel25.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel25.setText("YOUR DOCTOR ID :");
        jPanel14.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, -1, -1));

        jTextField7.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel14.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 190, 40));

        jPasswordField7.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jPanel14.add(jPasswordField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 190, 40));

        jPasswordField8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jPanel14.add(jPasswordField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 190, 40));

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jPanel14.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 190, 40));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-accept-60.png"))); // NOI18N
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 70, 70));

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-proceed-70.png"))); // NOI18N
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 90, 80));

        jPanel7.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 740, 510));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-thick-long-left-arrow-70.png"))); // NOI18N
        jLabel29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 70, 80));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signup5.jpg"))); // NOI18N
        jPanel7.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1200, 600));

        jTabbedPane1.addTab("", jPanel7);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 1200, 700));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signupbgr.jpg"))); // NOI18N
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 800));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1940, 1030));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        setVisible(false);
        new Mainpage().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Sginuppanel.setVisible(true);                  // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTabbedPane1.setSelectedIndex(1);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTabbedPane1.setSelectedIndex(2);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTabbedPane1.setSelectedIndex(3);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTabbedPane1.setSelectedIndex(4);// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        String text = jTextField1.getText();
        String text2 = jTextField5.getText();
        String password1 = new String(jPasswordField1.getPassword());
        String password2 = new String(jPasswordField2.getPassword());
        if (text.isEmpty() || password1.isEmpty() || password2.isEmpty() || text2.isEmpty()) {
            JOptionPane.showMessageDialog(null, "These fields cannot be empty.");
        } else {
            // Check if passwords match
            if (password1.equals(password2)) {
                Random rand = new Random();
                int randomNum = rand.nextInt((1001 - 1) + 1) + 1;
                jTextField2.setText("USR" + randomNum);
            } else {
                JOptionPane.showMessageDialog(null, "Passwords do not match. Please try again.");
                jPasswordField1.setText("");
                jPasswordField2.setText("");
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        String userName = jTextField1.getText();
        String localLoc = jTextField5.getText();
        String password1 = new String(jPasswordField1.getPassword());
        String password2 = new String(jPasswordField2.getPassword());
        if (userName.isEmpty() || password1.isEmpty() || password2.isEmpty() || jTextField2.getText().isEmpty() || localLoc.isEmpty()) {
            JOptionPane.showMessageDialog(null, "USER ID MUST BE GENERATED  OR Any Data removed from the fields");
        } else {
            //database code to be written saying  if userid is not present then save to database and take to next page else show optionpane with message generate another number
            String userId = jTextField2.getText();
            try {
                conn = getNewConnection();
                String query = "INSERT INTO DairyFarmer (User_Id, User_name, Local_loc,Password) VALUES (?, ?, ?,?)";
                PreparedStatement pstmt = conn.prepareStatement(query);
                //binding values
                pstmt.setString(1, userId);
                pstmt.setString(2, userName);
                pstmt.setString(3, localLoc);
                 pstmt.setString(4, password1);
                //executing the insert query
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Inserted");
                setVisible(false);
                new Mainpage().setVisible(true);
            } catch (SQLIntegrityConstraintViolationException e) {
                JOptionPane.showMessageDialog(null, "Regenerate User Id");
            } catch (SQLException e) {
                e.printStackTrace();
            }

        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String text = jTextField3.getText();
        String password1 = new String(jPasswordField3.getPassword());
        String password2 = new String(jPasswordField4.getPassword());
        if (text.isEmpty() || password1.isEmpty() || password2.isEmpty()) {
            JOptionPane.showMessageDialog(null, "These fields cannot be empty.");
        } else {
            // Check if passwords match
            if (password1.equals(password2)) {
                Random rand = new Random();
                int randomNum = rand.nextInt((1001 - 1) + 1) + 1;
                jTextField4.setText("MAN" + randomNum);
            } else {
                JOptionPane.showMessageDialog(null, "Passwords do not match. Please try again.");
                jPasswordField3.setText("");
                jPasswordField4.setText("");
            }
        }       // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        String manuName = jTextField3.getText();
        String password1 = new String(jPasswordField3.getPassword());
        String password2 = new String(jPasswordField4.getPassword());
        if (manuName.isEmpty() || password1.isEmpty() || password2.isEmpty() || jTextField4.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "MANU ID MUST BE GENERATED  OR Any Data removed from the fields");
        } else {
            try {
                String manuId = jTextField4.getText();
                conn = getNewConnection();
                
                PreparedStatement stmt = conn.prepareStatement("SELECT * FROM Feedman1 WHERE Manu_Id = ?");
                stmt.setString(1, manuId);
                ResultSet rs = stmt.executeQuery();

                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Manu Id already exists. Please regenerate the Manu_Id.");
                } else {
                    PreparedStatement stmt2 = conn.prepareStatement("INSERT INTO Feedman1( Manu_Id,Manu_Name,Password) values(?,?,?)");
                    
                    stmt2.setString(1, manuId);
                    stmt2.setString(2, manuName);
                    stmt2.setString(3, password1);
                    stmt2.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Manu_Name and Manu_Id inserted successfully.");
                    setVisible(false);
                    new Mainpage().setVisible(true);
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "An error occurred while inserting Manu_Name and Manu_Id.\n" + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String localLocation = Localloc.getText();
        String location = Location.getText();

        String password1 = new String(jPasswordField5.getPassword());
        String password2 = new String(jPasswordField6.getPassword());
        if (localLocation.isEmpty() || location.isEmpty() || password1.isEmpty() || password2.isEmpty()) {
            JOptionPane.showMessageDialog(null, "These fields cannot be empty.");
        } else {

            if (password1.equals(password2)) {
                Random rand = new Random();
                int randomNum = rand.nextInt((1001 - 1) + 1) + 1;
                Depotid.setText("DEP" + randomNum);
            } else {
                JOptionPane.showMessageDialog(null, "Passwords do not match. Please try again.");
                jPasswordField5.setText("");
                jPasswordField6.setText("");
            } // Do something else if location and local location do not exist in the Headoffice table
        }
    }//GEN-LAST:event_jButton7ActionPerformed
    Connection conn = null;

    private Connection getNewConnection() {
        conn = db.getConnection();
        return conn;
    }
    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        String localLoc = Localloc.getText();
        String location = Location.getText();
        String password1 = new String(jPasswordField5.getPassword());
        String password2 = new String(jPasswordField6.getPassword());
        if (localLoc.isEmpty() || password1.isEmpty() || password2.isEmpty() || Depotid.getText().isEmpty() || location.isEmpty()) {
            JOptionPane.showMessageDialog(null, "DEP ID MUST BE GENERATED  OR Any Data removed from the fields");
        } else {
            String depotId = Depotid.getText();
            conn = getNewConnection();
            try {
                String checkQuery = "SELECT COUNT(*) FROM MilkDepot WHERE Depot_Id = ?";
                PreparedStatement checkPstmt = conn.prepareStatement(checkQuery);
                checkPstmt.setString(1, depotId);
                ResultSet checkRs = checkPstmt.executeQuery();
                checkRs.next();
                int count = checkRs.getInt(1);
                if (count > 0) {
                    JOptionPane.showMessageDialog(null, "Depot ID already exists, please regenerate.");
                    return;
                }
                // Check if the location and localLoc match a record in the HeadOffice table
                String checkHeadofficeQuery = "SELECT COUNT(*) FROM Headoffice WHERE Location = ? AND Local_Loc = ?";
                PreparedStatement checkHeadofficePstmt = conn.prepareStatement(checkHeadofficeQuery);
                checkHeadofficePstmt.setString(1, location);
                checkHeadofficePstmt.setString(2, localLoc);
                ResultSet checkHeadofficeRs = checkHeadofficePstmt.executeQuery();
                checkHeadofficeRs.next();
                int headofficeCount = checkHeadofficeRs.getInt(1);
                if (headofficeCount > 0) {
                    JOptionPane.showMessageDialog(null, "Depot already exists there.");
                    return;
                }

                // Insert values into Headoffice table
                String headofficeQuery = "INSERT INTO Headoffice(Location, Local_Loc, Depot_Id) VALUES (?, ?, ?)";
                PreparedStatement headofficePstmt = conn.prepareStatement(headofficeQuery);
                headofficePstmt.setString(1, location);
                headofficePstmt.setString(2, localLoc);
                headofficePstmt.setString(3, depotId);
                headofficePstmt.executeUpdate();

// Insert values into MilkDepot table
                String milkdepotQuery = "INSERT INTO MilkDepot(Depot_Id, Local_Loc,Password) VALUES (?, ?, ?)";
                PreparedStatement milkdepotPstmt = conn.prepareStatement(milkdepotQuery);
                milkdepotPstmt.setString(1, depotId);
                milkdepotPstmt.setString(2, localLoc);
                 milkdepotPstmt.setString(3, password1);
                milkdepotPstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data inserted successfully!");

                //database code to be written saying  if userid is not present then save to database and take to next page else show optionpane with message generate another number
                setVisible(false);
                new Mainpage().setVisible(true);

            } catch (SQLException e) {
                e.printStackTrace();
            }

        }


    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String text = jTextField7.getText();

        String password1 = new String(jPasswordField7.getPassword());
        String password2 = new String(jPasswordField8.getPassword());
        if (text.isEmpty() || password1.isEmpty() || password2.isEmpty()) {
            JOptionPane.showMessageDialog(null, "These fields cannot be empty.");
        } else {
            // Check if passwords match
            if (password1.equals(password2)) {
                Random rand = new Random();
                int randomNum = rand.nextInt((1001 - 1) + 1) + 1;
                jTextField8.setText("DOC" + randomNum);
            } else {
                JOptionPane.showMessageDialog(null, "Passwords do not match. Please try again.");
                jPasswordField7.setText("");
                jPasswordField8.setText("");
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed

        String doctorName = jTextField7.getText();
        String password1 = new String(jPasswordField7.getPassword());
        String password2 = new String(jPasswordField8.getPassword());
        if (doctorName.isEmpty() || password1.isEmpty() || password2.isEmpty() || jTextField8.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "DOC ID MUST BE GENERATED OR Any Data removed from the fields");
        } else {
            try {
                String doctorId = jTextField8.getText();
                conn = getNewConnection();
                String checkQuery = "SELECT COUNT(*) FROM Doctor WHERE Doctor_Id = ?";
                PreparedStatement pstmt = conn.prepareStatement(checkQuery);
                pstmt.setString(1, doctorId);
                ResultSet rs = pstmt.executeQuery();
                if (rs.next() && rs.getInt(1) > 0) {
                    JOptionPane.showMessageDialog(null, "Doctor Id already exists, please regenerate it", "Error", JOptionPane.ERROR_MESSAGE);

                } else {
                    String insertQuery = "INSERT INTO Doctor (Doctor_Id, Doctor_Name,Password) VALUES (?, ?, ?)";
                    pstmt = conn.prepareStatement(insertQuery);
                    pstmt.setString(1, doctorId);
                    pstmt.setString(2, doctorName);
                    pstmt.setString(3, password1);
                    pstmt.executeUpdate();
                    JOptionPane.showOptionDialog(null, "Doctor added successfully", "Confirmation", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, new String[]{"OK"}, "OK");
                }
                //database code to be written saying  if userid is not present then save to database and take to next page else show optionpane with message generate another number
                setVisible(false);
                new Mainpage().setVisible(true);
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        jTabbedPane1.setSelectedIndex(0); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        jTabbedPane1.setSelectedIndex(0); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        jTabbedPane1.setSelectedIndex(0);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel31MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signuplogin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signuplogin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signuplogin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signuplogin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signuplogin_page().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Depotid;
    private javax.swing.JTextField Localloc;
    private javax.swing.JTextField Location;
    private javax.swing.JPanel Sginuppanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JPasswordField jPasswordField5;
    private javax.swing.JPasswordField jPasswordField6;
    private javax.swing.JPasswordField jPasswordField7;
    private javax.swing.JPasswordField jPasswordField8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
